/* tslint:disable */
/* eslint-disable */
/**
 * Your API v1
 * API v1 documentation with JWT authentication
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface AuthPost200Response
 */
export interface AuthPost200Response {
    /**
     * 
     * @type {string}
     * @memberof AuthPost200Response
     */
    'message'?: string;
    /**
     * JWT token for the authenticated user
     * @type {string}
     * @memberof AuthPost200Response
     */
    'data'?: string;
    /**
     * 
     * @type {number}
     * @memberof AuthPost200Response
     */
    'code'?: number;
}
/**
 * 
 * @export
 * @interface AuthPost400Response
 */
export interface AuthPost400Response {
    /**
     * 
     * @type {string}
     * @memberof AuthPost400Response
     */
    'message'?: string;
}
/**
 * 
 * @export
 * @interface AuthPostRequest
 */
export interface AuthPostRequest {
    /**
     * User\'s email address
     * @type {string}
     * @memberof AuthPostRequest
     */
    'email'?: string;
    /**
     * User\'s password
     * @type {string}
     * @memberof AuthPostRequest
     */
    'password'?: string;
}
/**
 * 
 * @export
 * @interface AuthenticationDTO
 */
export interface AuthenticationDTO {
    /**
     * 
     * @type {string}
     * @memberof AuthenticationDTO
     */
    'password'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationDTO
     */
    'username'?: string;
}
/**
 * 
 * @export
 * @interface CreateListingDTO
 */
export interface CreateListingDTO {
    /**
     * 
     * @type {string}
     * @memberof CreateListingDTO
     */
    'address'?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateListingDTO
     */
    'bathrooms'?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateListingDTO
     */
    'bedrooms'?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateListingDTO
     */
    'building_size'?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateListingDTO
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateListingDTO
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateListingDTO
     */
    'email'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateListingDTO
     */
    'images'?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof CreateListingDTO
     */
    'land_size'?: number;
    /**
     * 
     * @type {Price}
     * @memberof CreateListingDTO
     */
    'prices'?: Price;
    /**
     * 
     * @type {string}
     * @memberof CreateListingDTO
     */
    'property_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateListingDTO
     */
    'property_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateListingDTO
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateListingDTO
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateListingDTO
     */
    'zip_code'?: string;
}
/**
 * 
 * @export
 * @interface HouseDTO
 */
export interface HouseDTO {
    /**
     * 
     * @type {number}
     * @memberof HouseDTO
     */
    'acres'?: number;
    /**
     * 
     * @type {number}
     * @memberof HouseDTO
     */
    'bathrooms'?: number;
    /**
     * 
     * @type {number}
     * @memberof HouseDTO
     */
    'bedrooms'?: number;
    /**
     * 
     * @type {number}
     * @memberof HouseDTO
     */
    'living_space_size'?: number;
    /**
     * 
     * @type {string}
     * @memberof HouseDTO
     */
    'state'?: string;
    /**
     * 
     * @type {number}
     * @memberof HouseDTO
     */
    'zip_code'?: number;
}
/**
 * 
 * @export
 * @interface IProperty
 */
export interface IProperty {
    /**
     * 
     * @type {string}
     * @memberof IProperty
     */
    'address'?: string;
    /**
     * 
     * @type {number}
     * @memberof IProperty
     */
    'bathrooms'?: number;
    /**
     * 
     * @type {number}
     * @memberof IProperty
     */
    'bedrooms'?: number;
    /**
     * 
     * @type {number}
     * @memberof IProperty
     */
    'building_size'?: number;
    /**
     * 
     * @type {string}
     * @memberof IProperty
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof IProperty
     */
    'description'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof IProperty
     */
    'images'?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof IProperty
     */
    'land_size'?: number;
    /**
     * 
     * @type {Price}
     * @memberof IProperty
     */
    'prices'?: Price;
    /**
     * 
     * @type {string}
     * @memberof IProperty
     */
    'property_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof IProperty
     */
    'property_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof IProperty
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof IProperty
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof IProperty
     */
    'zip_code'?: string;
}
/**
 * 
 * @export
 * @interface ISoldProperty
 */
export interface ISoldProperty {
    /**
     * 
     * @type {number}
     * @memberof ISoldProperty
     */
    'acre_lot'?: number;
    /**
     * 
     * @type {number}
     * @memberof ISoldProperty
     */
    'bath'?: number;
    /**
     * 
     * @type {number}
     * @memberof ISoldProperty
     */
    'bed'?: number;
    /**
     * 
     * @type {string}
     * @memberof ISoldProperty
     */
    'city'?: string;
    /**
     * 
     * @type {number}
     * @memberof ISoldProperty
     */
    'house_size'?: number;
    /**
     * 
     * @type {string}
     * @memberof ISoldProperty
     */
    'prev_sold_data'?: string;
    /**
     * 
     * @type {number}
     * @memberof ISoldProperty
     */
    'price'?: number;
    /**
     * 
     * @type {string}
     * @memberof ISoldProperty
     */
    'state'?: string;
    /**
     * 
     * @type {number}
     * @memberof ISoldProperty
     */
    'street'?: number;
    /**
     * 
     * @type {string}
     * @memberof ISoldProperty
     */
    'zip_code'?: string;
}
/**
 * 
 * @export
 * @interface IUser
 */
export interface IUser {
    /**
     * 
     * @type {string}
     * @memberof IUser
     */
    '_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof IUser
     */
    'company'?: string;
    /**
     * 
     * @type {string}
     * @memberof IUser
     */
    'company_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof IUser
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof IUser
     */
    'first_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof IUser
     */
    'last_name'?: string;
    /**
     * 
     * @type {Array<IProperty>}
     * @memberof IUser
     */
    'listings'?: Array<IProperty>;
    /**
     * 
     * @type {string}
     * @memberof IUser
     */
    'password'?: string;
    /**
     * 
     * @type {string}
     * @memberof IUser
     */
    'phone_number'?: string;
    /**
     * 
     * @type {string}
     * @memberof IUser
     */
    'profile_pic'?: string;
    /**
     * 
     * @type {string}
     * @memberof IUser
     */
    'role'?: string;
    /**
     * 
     * @type {string}
     * @memberof IUser
     */
    'userName'?: string;
}
/**
 * 
 * @export
 * @interface ListingDetailed
 */
export interface ListingDetailed {
    /**
     * 
     * @type {string}
     * @memberof ListingDetailed
     */
    'address'?: string;
    /**
     * 
     * @type {number}
     * @memberof ListingDetailed
     */
    'bathrooms'?: number;
    /**
     * 
     * @type {number}
     * @memberof ListingDetailed
     */
    'bedrooms'?: number;
    /**
     * 
     * @type {number}
     * @memberof ListingDetailed
     */
    'building_size'?: number;
    /**
     * 
     * @type {string}
     * @memberof ListingDetailed
     */
    'city'?: string;
    /**
     * 
     * @type {ListingDetailedContact}
     * @memberof ListingDetailed
     */
    'contact'?: ListingDetailedContact;
    /**
     * 
     * @type {string}
     * @memberof ListingDetailed
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof ListingDetailed
     */
    'estimated_market_price'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ListingDetailed
     */
    'images'?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ListingDetailed
     */
    'land_size'?: number;
    /**
     * 
     * @type {Price}
     * @memberof ListingDetailed
     */
    'prices'?: Price;
    /**
     * 
     * @type {string}
     * @memberof ListingDetailed
     */
    'property_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ListingDetailed
     */
    'property_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof ListingDetailed
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof ListingDetailed
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof ListingDetailed
     */
    'zip_code'?: string;
}
/**
 * 
 * @export
 * @interface ListingDetailedContact
 */
export interface ListingDetailedContact {
    /**
     * 
     * @type {string}
     * @memberof ListingDetailedContact
     */
    'company'?: string;
    /**
     * 
     * @type {string}
     * @memberof ListingDetailedContact
     */
    'company_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof ListingDetailedContact
     */
    'first_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ListingDetailedContact
     */
    'last_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ListingDetailedContact
     */
    'phone_number'?: string;
    /**
     * 
     * @type {any}
     * @memberof ListingDetailedContact
     */
    'profile_pic'?: any;
}
/**
 * 
 * @export
 * @interface ListingIdDelete200Response
 */
export interface ListingIdDelete200Response {
    /**
     * 
     * @type {number}
     * @memberof ListingIdDelete200Response
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof ListingIdDelete200Response
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ListingIdDelete200Response
     */
    'data'?: boolean;
}
/**
 * 
 * @export
 * @interface ListingIdDelete400Response
 */
export interface ListingIdDelete400Response {
    /**
     * 
     * @type {number}
     * @memberof ListingIdDelete400Response
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof ListingIdDelete400Response
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ListingIdDelete400Response
     */
    'data'?: boolean;
}
/**
 * 
 * @export
 * @interface ListingIdDelete404Response
 */
export interface ListingIdDelete404Response {
    /**
     * 
     * @type {number}
     * @memberof ListingIdDelete404Response
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof ListingIdDelete404Response
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ListingIdDelete404Response
     */
    'data'?: boolean;
}
/**
 * 
 * @export
 * @interface ListingIdDelete500Response
 */
export interface ListingIdDelete500Response {
    /**
     * 
     * @type {number}
     * @memberof ListingIdDelete500Response
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof ListingIdDelete500Response
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ListingIdDelete500Response
     */
    'data'?: boolean;
}
/**
 * 
 * @export
 * @interface ListingIdGet200Response
 */
export interface ListingIdGet200Response {
    /**
     * 
     * @type {number}
     * @memberof ListingIdGet200Response
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof ListingIdGet200Response
     */
    'message'?: string;
    /**
     * 
     * @type {ListingDetailed}
     * @memberof ListingIdGet200Response
     */
    'data'?: ListingDetailed;
}
/**
 * 
 * @export
 * @interface ListingIdGet404Response
 */
export interface ListingIdGet404Response {
    /**
     * 
     * @type {number}
     * @memberof ListingIdGet404Response
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof ListingIdGet404Response
     */
    'message'?: string;
    /**
     * 
     * @type {object}
     * @memberof ListingIdGet404Response
     */
    'data'?: object;
}
/**
 * 
 * @export
 * @interface ListingIdGet500Response
 */
export interface ListingIdGet500Response {
    /**
     * 
     * @type {number}
     * @memberof ListingIdGet500Response
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof ListingIdGet500Response
     */
    'message'?: string;
    /**
     * 
     * @type {any}
     * @memberof ListingIdGet500Response
     */
    'data'?: any;
}
/**
 * 
 * @export
 * @interface ListingPost201Response
 */
export interface ListingPost201Response {
    /**
     * 
     * @type {number}
     * @memberof ListingPost201Response
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof ListingPost201Response
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ListingPost201Response
     */
    'data'?: boolean;
}
/**
 * 
 * @export
 * @interface ListingPost400Response
 */
export interface ListingPost400Response {
    /**
     * 
     * @type {number}
     * @memberof ListingPost400Response
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof ListingPost400Response
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ListingPost400Response
     */
    'data'?: boolean;
}
/**
 * 
 * @export
 * @interface ListingPost500Response
 */
export interface ListingPost500Response {
    /**
     * 
     * @type {number}
     * @memberof ListingPost500Response
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof ListingPost500Response
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ListingPost500Response
     */
    'data'?: boolean;
}
/**
 * 
 * @export
 * @interface ListingPut200Response
 */
export interface ListingPut200Response {
    /**
     * 
     * @type {number}
     * @memberof ListingPut200Response
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof ListingPut200Response
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ListingPut200Response
     */
    'data'?: boolean;
}
/**
 * 
 * @export
 * @interface ListingPut404Response
 */
export interface ListingPut404Response {
    /**
     * 
     * @type {number}
     * @memberof ListingPut404Response
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof ListingPut404Response
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ListingPut404Response
     */
    'data'?: boolean;
}
/**
 * 
 * @export
 * @interface ListingPut500Response
 */
export interface ListingPut500Response {
    /**
     * 
     * @type {number}
     * @memberof ListingPut500Response
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof ListingPut500Response
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ListingPut500Response
     */
    'data'?: boolean;
}
/**
 * 
 * @export
 * @interface ListingsAvailableGet400Response
 */
export interface ListingsAvailableGet400Response {
    /**
     * 
     * @type {string}
     * @memberof ListingsAvailableGet400Response
     */
    'error'?: string;
}
/**
 * 
 * @export
 * @interface ListingsAvailableGet404Response
 */
export interface ListingsAvailableGet404Response {
    /**
     * 
     * @type {string}
     * @memberof ListingsAvailableGet404Response
     */
    'message'?: string;
}
/**
 * 
 * @export
 * @interface ListingsAvailableGet500Response
 */
export interface ListingsAvailableGet500Response {
    /**
     * 
     * @type {string}
     * @memberof ListingsAvailableGet500Response
     */
    'error'?: string;
}
/**
 * 
 * @export
 * @interface ListingsAvailableZipCodePost200Response
 */
export interface ListingsAvailableZipCodePost200Response {
    /**
     * 
     * @type {number}
     * @memberof ListingsAvailableZipCodePost200Response
     */
    'total_number_of_listings'?: number;
    /**
     * 
     * @type {Array<ListingDetailed>}
     * @memberof ListingsAvailableZipCodePost200Response
     */
    'listings'?: Array<ListingDetailed>;
}
/**
 * 
 * @export
 * @interface ListingsAvailableZipCodePostRequest
 */
export interface ListingsAvailableZipCodePostRequest {
    /**
     * The number of listings to retrieve.
     * @type {number}
     * @memberof ListingsAvailableZipCodePostRequest
     */
    'number_of_listings'?: number;
}
/**
 * 
 * @export
 * @interface ListingsGet200Response
 */
export interface ListingsGet200Response {
    /**
     * 
     * @type {number}
     * @memberof ListingsGet200Response
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof ListingsGet200Response
     */
    'message'?: string;
    /**
     * 
     * @type {Array<ListingDetailed>}
     * @memberof ListingsGet200Response
     */
    'data'?: Array<ListingDetailed>;
}
/**
 * 
 * @export
 * @interface ListingsGet500Response
 */
export interface ListingsGet500Response {
    /**
     * 
     * @type {number}
     * @memberof ListingsGet500Response
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof ListingsGet500Response
     */
    'message'?: string;
    /**
     * 
     * @type {any}
     * @memberof ListingsGet500Response
     */
    'data'?: any;
}
/**
 * 
 * @export
 * @interface LoginDTO
 */
export interface LoginDTO {
    /**
     * 
     * @type {string}
     * @memberof LoginDTO
     */
    'password'?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginDTO
     */
    'username'?: string;
}
/**
 * 
 * @export
 * @interface Price
 */
export interface Price {
    /**
     * 
     * @type {number}
     * @memberof Price
     */
    'CAD'?: number;
    /**
     * 
     * @type {number}
     * @memberof Price
     */
    'EUR'?: number;
    /**
     * 
     * @type {number}
     * @memberof Price
     */
    'USD'?: number;
}
/**
 * 
 * @export
 * @interface RegisterPost201Response
 */
export interface RegisterPost201Response {
    /**
     * JWT token for the registered user
     * @type {string}
     * @memberof RegisterPost201Response
     */
    'data'?: string;
    /**
     * 
     * @type {number}
     * @memberof RegisterPost201Response
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof RegisterPost201Response
     */
    'message'?: string;
}
/**
 * 
 * @export
 * @interface RegisterPost400Response
 */
export interface RegisterPost400Response {
    /**
     * 
     * @type {string}
     * @memberof RegisterPost400Response
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof RegisterPost400Response
     */
    'code'?: number;
}
/**
 * 
 * @export
 * @interface RegisterPostRequest
 */
export interface RegisterPostRequest {
    /**
     * User\'s first name
     * @type {string}
     * @memberof RegisterPostRequest
     */
    'first_name'?: string;
    /**
     * User\'s last name
     * @type {string}
     * @memberof RegisterPostRequest
     */
    'last_name'?: string;
    /**
     * Name of the user\'s company (optional)
     * @type {string}
     * @memberof RegisterPostRequest
     */
    'company_name'?: string;
    /**
     * User\'s email address
     * @type {string}
     * @memberof RegisterPostRequest
     */
    'email'?: string;
    /**
     * User\'s password
     * @type {string}
     * @memberof RegisterPostRequest
     */
    'password'?: string;
    /**
     * User\'s phone number (optional)
     * @type {string}
     * @memberof RegisterPostRequest
     */
    'phone'?: string;
    /**
     * URL to the user\'s profile picture (optional)
     * @type {string}
     * @memberof RegisterPostRequest
     */
    'pfp'?: string;
}
/**
 * 
 * @export
 * @interface RegistrationDTO
 */
export interface RegistrationDTO {
    /**
     * 
     * @type {string}
     * @memberof RegistrationDTO
     */
    'company_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationDTO
     */
    'first_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationDTO
     */
    'last_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationDTO
     */
    'password'?: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationDTO
     */
    'phone_number'?: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationDTO
     */
    'profile_picture'?: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationDTO
     */
    'username'?: string;
}
/**
 * 
 * @export
 * @interface ResponseObject
 */
export interface ResponseObject {
    /**
     * 
     * @type {number}
     * @memberof ResponseObject
     */
    'code'?: number;
    /**
     * 
     * @type {object}
     * @memberof ResponseObject
     */
    'data'?: object;
    /**
     * 
     * @type {string}
     * @memberof ResponseObject
     */
    'message'?: string;
}
/**
 * 
 * @export
 * @enum {string}
 */

export const Role = {
    Admin: 'admin',
    User: 'user',
    Moderator: 'moderator',
    Guest: 'guest'
} as const;

export type Role = typeof Role[keyof typeof Role];


/**
 * 
 * @export
 * @interface UserTokenGet200Response
 */
export interface UserTokenGet200Response {
    /**
     * 
     * @type {number}
     * @memberof UserTokenGet200Response
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof UserTokenGet200Response
     */
    'message'?: string;
    /**
     * 
     * @type {IUser}
     * @memberof UserTokenGet200Response
     */
    'data'?: IUser;
}

/**
 * AuthenticationApi - axios parameter creator
 * @export
 */
export const AuthenticationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Authenticates a user with email and password, returning a JWT token upon success.
         * @summary Authenticate user
         * @param {AuthPostRequest} authPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authPost: async (authPostRequest: AuthPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authPostRequest' is not null or undefined
            assertParamExists('authPost', 'authPostRequest', authPostRequest)
            const localVarPath = `/auth`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(authPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Creates a new user account with the provided details.
         * @summary Register a new user
         * @param {RegisterPostRequest} registerPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerPost: async (registerPostRequest: RegisterPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'registerPostRequest' is not null or undefined
            assertParamExists('registerPost', 'registerPostRequest', registerPostRequest)
            const localVarPath = `/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(registerPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthenticationApi - functional programming interface
 * @export
 */
export const AuthenticationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthenticationApiAxiosParamCreator(configuration)
    return {
        /**
         * Authenticates a user with email and password, returning a JWT token upon success.
         * @summary Authenticate user
         * @param {AuthPostRequest} authPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authPost(authPostRequest: AuthPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authPost(authPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.authPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Creates a new user account with the provided details.
         * @summary Register a new user
         * @param {RegisterPostRequest} registerPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerPost(registerPostRequest: RegisterPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RegisterPost201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.registerPost(registerPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.registerPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthenticationApi - factory interface
 * @export
 */
export const AuthenticationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthenticationApiFp(configuration)
    return {
        /**
         * Authenticates a user with email and password, returning a JWT token upon success.
         * @summary Authenticate user
         * @param {AuthPostRequest} authPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authPost(authPostRequest: AuthPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<AuthPost200Response> {
            return localVarFp.authPost(authPostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Creates a new user account with the provided details.
         * @summary Register a new user
         * @param {RegisterPostRequest} registerPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerPost(registerPostRequest: RegisterPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<RegisterPost201Response> {
            return localVarFp.registerPost(registerPostRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthenticationApi - object-oriented interface
 * @export
 * @class AuthenticationApi
 * @extends {BaseAPI}
 */
export class AuthenticationApi extends BaseAPI {
    /**
     * Authenticates a user with email and password, returning a JWT token upon success.
     * @summary Authenticate user
     * @param {AuthPostRequest} authPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public authPost(authPostRequest: AuthPostRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).authPost(authPostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Creates a new user account with the provided details.
     * @summary Register a new user
     * @param {RegisterPostRequest} registerPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public registerPost(registerPostRequest: RegisterPostRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).registerPost(registerPostRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * HistoricDataApi - axios parameter creator
 * @export
 */
export const HistoricDataApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns the average price of properties grouped by the number of bathrooms.
         * @summary Get average price by bathrooms
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        historyAveragePriceByBathroomsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/history/average-price-by-bathrooms`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the average price of properties grouped by the number of bedrooms.
         * @summary Get average price by bedrooms
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        historyAveragePriceByBedroomsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/history/average-price-by-bedrooms`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the average price of properties for each state.
         * @summary Get average price by state
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        historyAveragePriceByStateGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/history/average-price-by-state`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the count of properties grouped by their size.
         * @summary Get property count by size
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        historyPropertiesCountBySizeGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/history/properties-count-by-size`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the count of properties for each state.
         * @summary Get property count by state
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        historyPropertiesCountByStateGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/history/properties-count-by-state`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the number of sales of properties grouped by year.
         * @summary Get sales by year
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        historySalesByYearGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/history/sales-by-year`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HistoricDataApi - functional programming interface
 * @export
 */
export const HistoricDataApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HistoricDataApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns the average price of properties grouped by the number of bathrooms.
         * @summary Get average price by bathrooms
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async historyAveragePriceByBathroomsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.historyAveragePriceByBathroomsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HistoricDataApi.historyAveragePriceByBathroomsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns the average price of properties grouped by the number of bedrooms.
         * @summary Get average price by bedrooms
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async historyAveragePriceByBedroomsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.historyAveragePriceByBedroomsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HistoricDataApi.historyAveragePriceByBedroomsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns the average price of properties for each state.
         * @summary Get average price by state
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async historyAveragePriceByStateGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.historyAveragePriceByStateGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HistoricDataApi.historyAveragePriceByStateGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns the count of properties grouped by their size.
         * @summary Get property count by size
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async historyPropertiesCountBySizeGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.historyPropertiesCountBySizeGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HistoricDataApi.historyPropertiesCountBySizeGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns the count of properties for each state.
         * @summary Get property count by state
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async historyPropertiesCountByStateGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.historyPropertiesCountByStateGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HistoricDataApi.historyPropertiesCountByStateGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns the number of sales of properties grouped by year.
         * @summary Get sales by year
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async historySalesByYearGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.historySalesByYearGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HistoricDataApi.historySalesByYearGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HistoricDataApi - factory interface
 * @export
 */
export const HistoricDataApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HistoricDataApiFp(configuration)
    return {
        /**
         * Returns the average price of properties grouped by the number of bathrooms.
         * @summary Get average price by bathrooms
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        historyAveragePriceByBathroomsGet(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.historyAveragePriceByBathroomsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the average price of properties grouped by the number of bedrooms.
         * @summary Get average price by bedrooms
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        historyAveragePriceByBedroomsGet(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.historyAveragePriceByBedroomsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the average price of properties for each state.
         * @summary Get average price by state
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        historyAveragePriceByStateGet(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.historyAveragePriceByStateGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the count of properties grouped by their size.
         * @summary Get property count by size
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        historyPropertiesCountBySizeGet(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.historyPropertiesCountBySizeGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the count of properties for each state.
         * @summary Get property count by state
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        historyPropertiesCountByStateGet(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.historyPropertiesCountByStateGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the number of sales of properties grouped by year.
         * @summary Get sales by year
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        historySalesByYearGet(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.historySalesByYearGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HistoricDataApi - object-oriented interface
 * @export
 * @class HistoricDataApi
 * @extends {BaseAPI}
 */
export class HistoricDataApi extends BaseAPI {
    /**
     * Returns the average price of properties grouped by the number of bathrooms.
     * @summary Get average price by bathrooms
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HistoricDataApi
     */
    public historyAveragePriceByBathroomsGet(options?: RawAxiosRequestConfig) {
        return HistoricDataApiFp(this.configuration).historyAveragePriceByBathroomsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the average price of properties grouped by the number of bedrooms.
     * @summary Get average price by bedrooms
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HistoricDataApi
     */
    public historyAveragePriceByBedroomsGet(options?: RawAxiosRequestConfig) {
        return HistoricDataApiFp(this.configuration).historyAveragePriceByBedroomsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the average price of properties for each state.
     * @summary Get average price by state
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HistoricDataApi
     */
    public historyAveragePriceByStateGet(options?: RawAxiosRequestConfig) {
        return HistoricDataApiFp(this.configuration).historyAveragePriceByStateGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the count of properties grouped by their size.
     * @summary Get property count by size
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HistoricDataApi
     */
    public historyPropertiesCountBySizeGet(options?: RawAxiosRequestConfig) {
        return HistoricDataApiFp(this.configuration).historyPropertiesCountBySizeGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the count of properties for each state.
     * @summary Get property count by state
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HistoricDataApi
     */
    public historyPropertiesCountByStateGet(options?: RawAxiosRequestConfig) {
        return HistoricDataApiFp(this.configuration).historyPropertiesCountByStateGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the number of sales of properties grouped by year.
     * @summary Get sales by year
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HistoricDataApi
     */
    public historySalesByYearGet(options?: RawAxiosRequestConfig) {
        return HistoricDataApiFp(this.configuration).historySalesByYearGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ListingsApi - axios parameter creator
 * @export
 */
export const ListingsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Deletes a specific listing from the database using the provided listing ID.
         * @summary Delete a listing by its ID
         * @param {string} id The ID of the listing to be deleted.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listingIdDelete: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('listingIdDelete', 'id', id)
            const localVarPath = `/listing/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves a specific property listing using its unique identifier.
         * @summary Get a specific listing by ID
         * @param {string} id Unique identifier for the listing.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listingIdGet: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('listingIdGet', 'id', id)
            const localVarPath = `/listing/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Adds a new property listing to a user\'s profile.
         * @summary Create a new listing for a user
         * @param {CreateListingDTO} createListingDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listingPost: async (createListingDTO: CreateListingDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createListingDTO' is not null or undefined
            assertParamExists('listingPost', 'createListingDTO', createListingDTO)
            const localVarPath = `/listing`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createListingDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Updates an existing property listing with the provided details.
         * @summary Edit an existing listing
         * @param {CreateListingDTO} createListingDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listingPut: async (createListingDTO: CreateListingDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createListingDTO' is not null or undefined
            assertParamExists('listingPut', 'createListingDTO', createListingDTO)
            const localVarPath = `/listing`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createListingDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Fetches all the property listings from the system.
         * @summary Retrieve all listings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listingsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/listings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ListingsApi - functional programming interface
 * @export
 */
export const ListingsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ListingsApiAxiosParamCreator(configuration)
    return {
        /**
         * Deletes a specific listing from the database using the provided listing ID.
         * @summary Delete a listing by its ID
         * @param {string} id The ID of the listing to be deleted.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listingIdDelete(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListingIdDelete200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listingIdDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ListingsApi.listingIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves a specific property listing using its unique identifier.
         * @summary Get a specific listing by ID
         * @param {string} id Unique identifier for the listing.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listingIdGet(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListingIdGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listingIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ListingsApi.listingIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Adds a new property listing to a user\'s profile.
         * @summary Create a new listing for a user
         * @param {CreateListingDTO} createListingDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listingPost(createListingDTO: CreateListingDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListingPost201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listingPost(createListingDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ListingsApi.listingPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Updates an existing property listing with the provided details.
         * @summary Edit an existing listing
         * @param {CreateListingDTO} createListingDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listingPut(createListingDTO: CreateListingDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListingPut200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listingPut(createListingDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ListingsApi.listingPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Fetches all the property listings from the system.
         * @summary Retrieve all listings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listingsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListingsGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listingsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ListingsApi.listingsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ListingsApi - factory interface
 * @export
 */
export const ListingsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ListingsApiFp(configuration)
    return {
        /**
         * Deletes a specific listing from the database using the provided listing ID.
         * @summary Delete a listing by its ID
         * @param {string} id The ID of the listing to be deleted.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listingIdDelete(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ListingIdDelete200Response> {
            return localVarFp.listingIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves a specific property listing using its unique identifier.
         * @summary Get a specific listing by ID
         * @param {string} id Unique identifier for the listing.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listingIdGet(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ListingIdGet200Response> {
            return localVarFp.listingIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Adds a new property listing to a user\'s profile.
         * @summary Create a new listing for a user
         * @param {CreateListingDTO} createListingDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listingPost(createListingDTO: CreateListingDTO, options?: RawAxiosRequestConfig): AxiosPromise<ListingPost201Response> {
            return localVarFp.listingPost(createListingDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * Updates an existing property listing with the provided details.
         * @summary Edit an existing listing
         * @param {CreateListingDTO} createListingDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listingPut(createListingDTO: CreateListingDTO, options?: RawAxiosRequestConfig): AxiosPromise<ListingPut200Response> {
            return localVarFp.listingPut(createListingDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * Fetches all the property listings from the system.
         * @summary Retrieve all listings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listingsGet(options?: RawAxiosRequestConfig): AxiosPromise<ListingsGet200Response> {
            return localVarFp.listingsGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ListingsApi - object-oriented interface
 * @export
 * @class ListingsApi
 * @extends {BaseAPI}
 */
export class ListingsApi extends BaseAPI {
    /**
     * Deletes a specific listing from the database using the provided listing ID.
     * @summary Delete a listing by its ID
     * @param {string} id The ID of the listing to be deleted.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListingsApi
     */
    public listingIdDelete(id: string, options?: RawAxiosRequestConfig) {
        return ListingsApiFp(this.configuration).listingIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves a specific property listing using its unique identifier.
     * @summary Get a specific listing by ID
     * @param {string} id Unique identifier for the listing.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListingsApi
     */
    public listingIdGet(id: string, options?: RawAxiosRequestConfig) {
        return ListingsApiFp(this.configuration).listingIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Adds a new property listing to a user\'s profile.
     * @summary Create a new listing for a user
     * @param {CreateListingDTO} createListingDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListingsApi
     */
    public listingPost(createListingDTO: CreateListingDTO, options?: RawAxiosRequestConfig) {
        return ListingsApiFp(this.configuration).listingPost(createListingDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Updates an existing property listing with the provided details.
     * @summary Edit an existing listing
     * @param {CreateListingDTO} createListingDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListingsApi
     */
    public listingPut(createListingDTO: CreateListingDTO, options?: RawAxiosRequestConfig) {
        return ListingsApiFp(this.configuration).listingPut(createListingDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Fetches all the property listings from the system.
     * @summary Retrieve all listings
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListingsApi
     */
    public listingsGet(options?: RawAxiosRequestConfig) {
        return ListingsApiFp(this.configuration).listingsGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * RealEstateAPIApi - axios parameter creator
 * @export
 */
export const RealEstateAPIApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves detailed property information using the provided listing URL.
         * @summary Fetch property details for a given listing URL.
         * @param {string} listingUrl The URL of the property listing to fetch details for.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listingsAvailableGet: async (listingUrl: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'listingUrl' is not null or undefined
            assertParamExists('listingsAvailableGet', 'listingUrl', listingUrl)
            const localVarPath = `/listings/available/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (listingUrl !== undefined) {
                localVarQueryParameter['listingUrl'] = listingUrl;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve a list of available properties based on the zip code and optionally the number of listings to retrieve.
         * @summary Retrieve a list of available properties
         * @param {string} zipCode The zip code to search for properties in.
         * @param {ListingsAvailableZipCodePostRequest} [listingsAvailableZipCodePostRequest] Optional body parameter to specify the number of listings to retrieve.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listingsAvailableZipCodePost: async (zipCode: string, listingsAvailableZipCodePostRequest?: ListingsAvailableZipCodePostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'zipCode' is not null or undefined
            assertParamExists('listingsAvailableZipCodePost', 'zipCode', zipCode)
            const localVarPath = `/listings/available/{zip_code}`
                .replace(`{${"zip_code"}}`, encodeURIComponent(String(zipCode)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(listingsAvailableZipCodePostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RealEstateAPIApi - functional programming interface
 * @export
 */
export const RealEstateAPIApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RealEstateAPIApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieves detailed property information using the provided listing URL.
         * @summary Fetch property details for a given listing URL.
         * @param {string} listingUrl The URL of the property listing to fetch details for.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listingsAvailableGet(listingUrl: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListingDetailed>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listingsAvailableGet(listingUrl, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RealEstateAPIApi.listingsAvailableGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve a list of available properties based on the zip code and optionally the number of listings to retrieve.
         * @summary Retrieve a list of available properties
         * @param {string} zipCode The zip code to search for properties in.
         * @param {ListingsAvailableZipCodePostRequest} [listingsAvailableZipCodePostRequest] Optional body parameter to specify the number of listings to retrieve.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listingsAvailableZipCodePost(zipCode: string, listingsAvailableZipCodePostRequest?: ListingsAvailableZipCodePostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListingsAvailableZipCodePost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listingsAvailableZipCodePost(zipCode, listingsAvailableZipCodePostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RealEstateAPIApi.listingsAvailableZipCodePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RealEstateAPIApi - factory interface
 * @export
 */
export const RealEstateAPIApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RealEstateAPIApiFp(configuration)
    return {
        /**
         * Retrieves detailed property information using the provided listing URL.
         * @summary Fetch property details for a given listing URL.
         * @param {string} listingUrl The URL of the property listing to fetch details for.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listingsAvailableGet(listingUrl: string, options?: RawAxiosRequestConfig): AxiosPromise<ListingDetailed> {
            return localVarFp.listingsAvailableGet(listingUrl, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve a list of available properties based on the zip code and optionally the number of listings to retrieve.
         * @summary Retrieve a list of available properties
         * @param {string} zipCode The zip code to search for properties in.
         * @param {ListingsAvailableZipCodePostRequest} [listingsAvailableZipCodePostRequest] Optional body parameter to specify the number of listings to retrieve.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listingsAvailableZipCodePost(zipCode: string, listingsAvailableZipCodePostRequest?: ListingsAvailableZipCodePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ListingsAvailableZipCodePost200Response> {
            return localVarFp.listingsAvailableZipCodePost(zipCode, listingsAvailableZipCodePostRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RealEstateAPIApi - object-oriented interface
 * @export
 * @class RealEstateAPIApi
 * @extends {BaseAPI}
 */
export class RealEstateAPIApi extends BaseAPI {
    /**
     * Retrieves detailed property information using the provided listing URL.
     * @summary Fetch property details for a given listing URL.
     * @param {string} listingUrl The URL of the property listing to fetch details for.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RealEstateAPIApi
     */
    public listingsAvailableGet(listingUrl: string, options?: RawAxiosRequestConfig) {
        return RealEstateAPIApiFp(this.configuration).listingsAvailableGet(listingUrl, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve a list of available properties based on the zip code and optionally the number of listings to retrieve.
     * @summary Retrieve a list of available properties
     * @param {string} zipCode The zip code to search for properties in.
     * @param {ListingsAvailableZipCodePostRequest} [listingsAvailableZipCodePostRequest] Optional body parameter to specify the number of listings to retrieve.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RealEstateAPIApi
     */
    public listingsAvailableZipCodePost(zipCode: string, listingsAvailableZipCodePostRequest?: ListingsAvailableZipCodePostRequest, options?: RawAxiosRequestConfig) {
        return RealEstateAPIApiFp(this.configuration).listingsAvailableZipCodePost(zipCode, listingsAvailableZipCodePostRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UsersApi - axios parameter creator
 * @export
 */
export const UsersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves a specific user from values in an access token.
         * @summary Gets a user by a valid token.
         * @param {string} token JWT
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userTokenGet: async (token: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'token' is not null or undefined
            assertParamExists('userTokenGet', 'token', token)
            const localVarPath = `/user/{token}`
                .replace(`{${"token"}}`, encodeURIComponent(String(token)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve a list of users from the API. Can be used to populate a list of users in your system.
         * @summary Retrieve a list of users
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersApi - functional programming interface
 * @export
 */
export const UsersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UsersApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieves a specific user from values in an access token.
         * @summary Gets a user by a valid token.
         * @param {string} token JWT
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userTokenGet(token: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserTokenGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userTokenGet(token, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.userTokenGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve a list of users from the API. Can be used to populate a list of users in your system.
         * @summary Retrieve a list of users
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<IUser>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.usersGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UsersApi - factory interface
 * @export
 */
export const UsersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsersApiFp(configuration)
    return {
        /**
         * Retrieves a specific user from values in an access token.
         * @summary Gets a user by a valid token.
         * @param {string} token JWT
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userTokenGet(token: string, options?: RawAxiosRequestConfig): AxiosPromise<UserTokenGet200Response> {
            return localVarFp.userTokenGet(token, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve a list of users from the API. Can be used to populate a list of users in your system.
         * @summary Retrieve a list of users
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<IUser>> {
            return localVarFp.usersGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UsersApi - object-oriented interface
 * @export
 * @class UsersApi
 * @extends {BaseAPI}
 */
export class UsersApi extends BaseAPI {
    /**
     * Retrieves a specific user from values in an access token.
     * @summary Gets a user by a valid token.
     * @param {string} token JWT
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public userTokenGet(token: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).userTokenGet(token, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve a list of users from the API. Can be used to populate a list of users in your system.
     * @summary Retrieve a list of users
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public usersGet(options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).usersGet(options).then((request) => request(this.axios, this.basePath));
    }
}



